# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  tests: true
  timeout: 10m

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  misspell:
    locale: US
  revive:
    rules:
      - name: var-naming
        disabled: true
  stylecheck:
    checks: ["all", "-ST1003"]
  unused:
    check-exported: false
  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    - copyloopvar
    - depguard
    - exhaustruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gci
    - gochecknoglobals
    - intrange
    - ireturn
    - lll
    - mnd
    - nlreturn
    - nonamedreturns
    - nolintlint # https://github.com/golangci/golangci-lint/issues/3063
    - paralleltest
    - tagalign
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck

issues:
  max-same-issues: 50
  exclude-use-default: false
  exclude-rules:
    - linters:
        - dupl
        - funlen
        - goconst
        - err113
        - mnd
        - noctx
      path: "_test.go"
